# Gitlab CI
# =========
#
# Each time we make a change to our Dockerfiles in PRP/docker/ we build the
# images and push them to the Nautilus container repository.
#
image: gcr.io/kaniko-project/executor:debug

stages:
  - build-and-push

build-and-push-job:
  stage: build-and-push
  # Look for changes in our docker folder
  #
  # We can define a space-separated string of image names we want to build and
  # push below.
  variables:
    DOCKERFILES_DIR: PRP/docker
    IMAGES: kubempi-ior torch-darshan
  rules:
    - changes:
        - $DOCKERFILES_DIR/Dockerfile.*
  # Let's see if kaniko lets us do multiple images at once -- we may need to
  # pass `--cleanup`...
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    # v This is a folded scalar which collapses the whitespace below.
    - >-
      for img in $IMAGES; do
      /kaniko/executor --cache=true --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/$DOCKERFILES_DIR/Dockerfile.${img}
      --destination $CI_REGISTRY_IMAGE/${img}:${CI_COMMIT_SHA:0:8}
      --destination $CI_REGISTRY_IMAGE/${img}:latest
      ; done
