# Gitlab CI
# =========
#
# Each time we make a change to our Dockerfiles in PRP/docker/ we build the
# images and push them to the Nautilus container repository.
#
# I tried getting away with multiple images in a single stage, but that didn't
# quite work, so instead I'm using a separate stage for each image we want to
# build and push.
#
image: gcr.io/kaniko-project/executor:debug

stages:
  - kubempi-ior
  - torch-darshan

kubempi-ior:
  stage: &NAME1 kubempi-ior
  variables:
    DOCKERFILES_DIR: PRP/docker
    IMAGE_NAME: *NAME1
  rules: &RULE
    - changes:
        - $DOCKERFILES_DIR/Dockerfile.$IMAGE_NAME
      when: always
  script: &SCRIPT
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor --cache=true --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/$DOCKERFILES_DIR/Dockerfile.$IMAGE_NAME
      --destination $CI_REGISTRY_IMAGE/$IMAGE_NAME:${CI_COMMIT_SHA:0:8}
      --destination $CI_REGISTRY_IMAGE/$IMAGE_NAME:latest

torch-darshan:
  stage: &NAME2 torch-darshan
  variables:
    DOCKERFILES_DIR: PRP/docker
    IMAGE_NAME: *NAME2
  rules: *RULE
  script: *SCRIPT
