# Minimal deployment
# ==================
#
# Launch a very minimal pod connect to a storage mount.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &NAME deploy-tf
spec:
  selector:
    matchLabels:
      app: *NAME
  template:
    metadata:
      labels:
        app: *NAME
    spec:
      containers:
      - name: *NAME
        # image: gitlab-registry.nautilus.optiputer.net/parkeraddison/filesystem-benchmarks/kubempi-ior
        # image: gitlab-registry.nautilus.optiputer.net/parkeraddison/filesystem-benchmarks/torch-darshan
        image: gitlab-registry.nautilus.optiputer.net/parkeraddison/filesystem-benchmarks/tf-darshan
        resources:
          limits: &RESOURCES
            cpu: 4
            memory: 8Gi
            nvidia.com/gpu: 1
          requests: *RESOURCES
        ports:
        - containerPort: 80
        tty: true
        command: [/bin/sh]
        args: [-c, sleep 999d]
# --- Change the lines below to test different storage types ----------------- #
        volumeMounts:
          - name: &VOLNAME shared-cephfs
            mountPath: /data
      volumes:
      - name: *VOLNAME
        persistentVolumeClaim:
          claimName: *VOLNAME
# --- Specify node selection/affinities here --------------------------------- #
      nodeSelector:
        topology.kubernetes.io/zone: ucsd
