# Minimal deployment
# ==================
#
# Launch a very minimal pod connect to a storage mount.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &NAME deploy-cephfs
spec:
  selector:
    matchLabels:
      app: *NAME
  template:
    metadata:
      labels:
        app: *NAME
    spec:
      containers:
      - name: *NAME
        image: parkeraddison/kube-openmpi-ior:0.7.0
        resources:
          limits: &RESOURCES
            cpu: 2
            memory: 4Gi
          requests: *RESOURCES
            # memory: "8Gi"
            # cpu: "8"
        ports:
        - containerPort: 80
        tty: true
        command: [/bin/sh]
        args: [-c, sleep 999d]
# --- Change the lines below to test different storage types ----------------- #
        volumeMounts:
          - name: &VOLNAME shared-cephfs
            mountPath: /data
      volumes:
      - name: *VOLNAME
        persistentVolumeClaim:
          claimName: *VOLNAME
# --- Specify node selection/affinities here --------------------------------- #
      nodeSelector:
        topology.kubernetes.io/zone: ucsd
